# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/student/Desktop/fourBitMult/fourBitMult.srcs/sources_1/ip/mult_gen/mult_gen.xci
# IP: The module: 'mult_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Desktop/fourBitMult/fourBitMult.srcs/sources_1/ip/mult_gen/mult_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/student/Desktop/fourBitMult/fourBitMult.srcs/sources_1/ip/mult_gen/mult_gen.xci
# IP: The module: 'mult_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Desktop/fourBitMult/fourBitMult.srcs/sources_1/ip/mult_gen/mult_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
